services:
  dev-image:
    build:
      dockerfile: $DOCKERFILE
      context: $PWD
    container_name: $COMPOSE_PROJECT_NAME-dev-container
    environment:
      CI:
    user: $HOST_UID:$HOST_GID
    volumes:
      - $DOCKER_GROUP_FILE:/etc/group:ro
      - $DOCKER_PASSWD_FILE:/etc/passwd:ro
      - $PWD:$PWD
    working_dir: $PWD
